#!/usr/bin/env python3
"""
render_wh_seed_wave.py — wh_query seed-wave generator (r43, design §2.4).

Reads db/shard-templates/ (manifest.json + <slug>.sql body-of-record) and
renders the per-shard SEED SQL wave:

  * one `insert into public.wh_query_templates (...) values (...)
    on conflict (template_hash) do nothing;` per template — the body literal is
    embedded as a dollar-quoted string ($body$ … $body$; the renderer aborts if
    a body ever contained the delimiter, so no collision is possible). The
    INSERT is a single statement, splittable on top-level semicolons.
  * one `grant select on <backing table> to wh_executor;` per template's
    logical_table (per §4.2: per-table, wave-managed, per template).
  * W5-class cold templates additionally:
      `grant execute on function public.unpack_block(b public.facts_blocks) to wh_executor;`
    — emitted ONLY with --with-cold, because it requires the columnar DDL
    (facts_blocks + unpack_block, findings_wh_columnar_loading.md §1.4) to
    exist on the shard FIRST.
  * a wave-terminating `notify pgrst, 'reload schema';` (r42 errata F5).

ORDERING LAW (r42 errata F9): apply the STATIC wave (0015: role, registry,
executor function, ACLs) FIRST, then THIS seed wave; template seed AND the
wh_executor backing-table grants below must be verified COMPLETE before the FM
job's finalize flips the shard to serving — a mid-wave shard is naturally
wh_query-ineligible (incomplete inventory fails the §5.2 handshake).

TRANSPORT (SKILL §5:167): the Supabase Management SQL API accepts ONE
statement per call (split this file on top-level semicolons with
dollar-quote awareness; the same semantics as scripts/sql_split.awk), and
`parameters[]` binding is available for the body literal as an alternative to
the embedded dollar-quoted string — the hash law (§2.3) is transport-blind:
sha256 is computed over the exact template-file bytes, which is what the
registry row must receive.

The renderer re-verifies every manifest hash against the template file bytes
before rendering (the §2.3 byte law, s297 byte-verify) and refuses to emit
anything on a mismatch. Re-applying the output is safe: `on conflict do
nothing` makes a hash-collision re-run a no-op, and a body drift is a loud PK
mismatch in the verify pass (§2.3 (b)).

Usage:
  python3 scripts/render_wh_seed_wave.py [--templates-dir DIR] [--out FILE]
                                         [--with-cold]
"""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATES_DIR_DEFAULT = REPO_ROOT / "db" / "shard-templates"
BODY_DELIM = "$body$"

COLD_QC_CLASSES = {"COLD_AGG"}
IDENT_RE = re.compile(r"[a-z_][a-z0-9_]*\Z")
# r43-F19 + audit-a F-A/F-B: shape-scan regexes — STRING LITERALS first
# ('' doubling handled), then block comments (DOTALL = the PG ARE 'gs' flag),
# then line comments. Order is load-bearing; mirrors wh_body_effective.
LITERAL_RE = re.compile(r"'([^']|'')*'")
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT_RE = re.compile(r"--[^\n]*")
ROWS_AGG_BAN_RE = re.compile(r"\b(jsonb_agg|array_agg|string_agg)\s*\(", re.IGNORECASE)
LIMIT2_ANCHOR_RE = re.compile(r"limit\s+\$2\s*\Z", re.IGNORECASE)

HEADER = """\
-- =============================================================================
-- wh_query SEED WAVE — template rows + wh_executor backing-table grants (r43)
-- =============================================================================
-- GENERATED by scripts/render_wh_seed_wave.py from db/shard-templates/
-- (manifest.json + <slug>.sql body-of-record). Do not edit by hand: the
-- template_hash pins sha256 over the EXACT template-file bytes (§2.3 hash law,
-- LF, no trailing newline); any body edit yields a new hash and a new row.
--
-- APPLY TARGET: each serving shard via the Supabase Management SQL API —
-- ONE STATEMENT PER CALL (split on top-level semicolons, dollar-quote aware);
-- `parameters[]` binding is available for the body literal as an alternative
-- to the embedded {delim}…{delim} string.
--
-- PREREQUISITES (in order, r42 errata F5/F9):
--   1. the STATIC wave (db/shard-migrations/0015_wh_query_rpc.sql) applied on
--      the shard: wh_executor role, public.wh_query_templates registry, the
--      public.wh_query(text, jsonb) executor function, ACLs, RLS, the
--      service_role role-GUC statement_timeout arm (r43-F18);
--   2. for --with-cold waves: the columnar DDL (public.facts_blocks +
--      public.unpack_block, findings_wh_columnar_loading.md §1.4) applied;
--   3. THIS wave: the INSERTs + grants below;
--   4. the FM job's finalize flips the shard to serving ONLY after template
--      seed AND the wh_executor grants are verified COMPLETE (ordering law
--      F9) — a mid-wave shard fails the engine's §5.2 inventory handshake and
--      is naturally wh_query-ineligible.
--
-- IDEMPOTENCY: `on conflict (template_hash) do nothing` — a re-run of this
-- wave is a no-op (hash collision = same bytes); a body drift can NOT land
-- here (the hash IS the PK) and would surface as a WH403 at execution time.
-- Grants are no-ops when already present.
-- {ncold}
-- =============================================================================
"""


def die(msg: str) -> None:
    print(f"render_wh_seed_wave: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def sql_quote(s: str) -> str:
    """Single-quoted SQL string literal ('' escaping)."""
    return "'" + s.replace("'", "''") + "'"


def main() -> int:
    ap = argparse.ArgumentParser(description="render the wh_query seed wave SQL")
    ap.add_argument("--templates-dir", default=str(TEMPLATES_DIR_DEFAULT),
                    help="dir holding manifest.json + template .sql files")
    ap.add_argument("--out", default=None, help="output path (default: stdout)")
    ap.add_argument("--with-cold", action="store_true",
                    help="emit the COLD_AGG unpack_block() execute grant (requires "
                         "the columnar facts_blocks DDL on the shard first)")
    args = ap.parse_args()

    tdir = Path(args.templates_dir)
    mpath = tdir / "manifest.json"
    if not mpath.is_file():
        die(f"manifest missing: {mpath}")
    try:
        manifest = json.loads(mpath.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        die(f"manifest.json is not valid JSON: {e}")
    if not isinstance(manifest, list) or not manifest:
        die("manifest.json must be a non-empty array")

    # ---- byte law verify pass (refuse to render on any mismatch) ------------
    rows = []
    for e in manifest:
        fpath = tdir / e.get("file", "")
        if not fpath.is_file():
            die(f"template file missing: {fpath}")
        raw = fpath.read_bytes()
        if b"\r" in raw:
            die(f"{e.get('file')}: CR bytes present (byte law: LF only)")
        if raw.endswith(b"\n"):
            die(f"{e.get('file')}: trailing newline (byte law: no trailing LF)")
        body = raw.decode("utf-8")
        h = hashlib.sha256(raw).hexdigest()
        if h != e.get("template_hash"):
            die(f"{e.get('file')}: sha256 {h} != manifest hash {e.get('template_hash')} "
                f"— file bytes differ from the pinned fence (trailing newline, "
                f"whitespace, smart quotes?); fix the BYTES, never the pin")
        if BODY_DELIM in body:
            die(f"{e.get('file')}: body contains the dollar-quote delimiter {BODY_DELIM}")
        if e.get("kind") == "rows":
            # audit-a F-A/F-B shape text: STRING LITERALS blanked FIRST, then
            # block comments (DOTALL = the 'gs' flag), then line comments —
            # mirrors the SQL-side wh_body_effective + the lint.
            eff = LINE_COMMENT_RE.sub(" ", BLOCK_COMMENT_RE.sub(" ", LITERAL_RE.sub(" ", body)))
            if not LIMIT2_ANCHOR_RE.search(eff) or "_pre_trim" not in eff:
                die(f"{e.get('file')}: rows-kind body violates the F2 sentinel shape "
                    f"(shape text must end `limit $2` and emit `_pre_trim`)")
            if ROWS_AGG_BAN_RE.search(eff):
                die(f"{e.get('file')}: rows-kind body contains a row-aggregate wrapper "
                    f"(jsonb_agg/array_agg/string_agg) — blob smuggling defeats the cap (r43-F19)")
            if '"' in eff:
                die(f"{e.get('file')}: rows-kind body contains a double quote — quoted "
                    f"identifiers bypass the agg ban (audit-a F-A); unquote or rename")
        lt = e.get("logical_table")
        if not isinstance(lt, str) or not IDENT_RE.fullmatch(lt):
            # audit-b P2-6: the GRANT below interpolates logical_table RAW —
            # a meta-character value would split it into attacker statements.
            die(f"{e.get('file')}: logical_table {lt!r} is not identifier-safe "
                f"(must match [a-z_][a-z0-9_]*)")
        rows.append((e, body))

    ncold = sum(1 for e, _ in rows if e.get("qc_class") in COLD_QC_CLASSES)
    if ncold and not args.with_cold:
        print(f"render_wh_seed_wave: note: manifest holds {ncold} COLD_AGG template(s); "
              f"pass --with-cold to emit the unpack_block() execute grant",
              file=sys.stderr)

    out = []
    out.append(HEADER.format(delim=BODY_DELIM, ncold="").rstrip())
    out.append("")

    for e, body in rows:
        slug = e.get("slug", "?")
        out.append(f"-- ---- template {slug} (sha256 {e['template_hash'][:16]}…) ----")
        # BYTE LAW: the body literal is emitted with NO added whitespace —
        # $body$ + exact file bytes + $body$ — so the registry row's body is
        # byte-identical to the body-of-record file and sha256(body) equals the
        # PK (the executor's step-(3b) runtime re-verify would WH403 otherwise).
        out.append(
            "insert into public.wh_query_templates\n"
            "  (template_hash, logical_table, qc_class, kind, body, params_schema,\n"
            "   merge_ops, group_keys, aggs, encoding, timeout_ms, max_rows,\n"
            "   schema_version, state)\n"
            "values\n"
            f"  ({sql_quote(e['template_hash'])},\n"
            f"   {sql_quote(e['logical_table'])},\n"
            f"   {sql_quote(e['qc_class'])},\n"
            f"   {sql_quote(e['kind'])},\n"
            f"   {BODY_DELIM}{body}{BODY_DELIM},\n"
            f"   {sql_quote(json.dumps(e.get('params_schema') or {}))}::jsonb,\n"
            f"   {sql_quote(json.dumps(e.get('merge_ops') or []))}::jsonb,\n"
            f"   {sql_quote(json.dumps(e.get('group_keys') or []))}::jsonb,\n"
            f"   {sql_quote(json.dumps(e.get('aggs') or {}))}::jsonb,\n"
            f"   {sql_quote(json.dumps(e.get('encoding') or {}))}::jsonb,\n"
            f"   {int(e['timeout_ms'])},\n"
            f"   {int(e['max_rows'])},\n"
            f"   {int(e['schema_version'])},\n"
            f"   {sql_quote(e['state'])})\n"
            "on conflict (template_hash) do nothing;"
        )
        out.append("")
        # per-template backing-table grant (§4.2: per-table, wave-managed)
        out.append(f"grant select on public.{e['logical_table']} to wh_executor;  -- {slug}")
        if e.get("qc_class") in COLD_QC_CLASSES and args.with_cold:
            out.append(
                f"grant execute on function public.unpack_block(b public.facts_blocks) "
                f"to wh_executor;  -- {slug} (COLD_AGG; columnar §1.4 DDL is a prerequisite)"
            )
        out.append("")

    out.append("-- ---- wave-terminating PostgREST schema-cache reload (r42 errata F5) ----")
    out.append("notify pgrst, 'reload schema';")
    out.append("")

    text = "\n".join(out)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"render_wh_seed_wave: wrote {args.out} "
              f"({len(rows)} template(s), byte-law hash-verify PASS)", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
